# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myFirstGrpc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11myFirstGrpc.proto\x12\x0bmyfirstgrpc\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1c\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\xe7\x02\n\x07Greeter\x12@\n\x08SayHello\x12\x19.myfirstgrpc.HelloRequest\x1a\x17.myfirstgrpc.HelloReply\"\x00\x12I\n\x0fStreamGreetings\x12\x19.myfirstgrpc.HelloRequest\x1a\x17.myfirstgrpc.HelloReply\"\x00\x30\x01\x12G\n\rSendGreetings\x12\x19.myfirstgrpc.HelloRequest\x1a\x17.myfirstgrpc.HelloReply\"\x00(\x01\x12@\n\x04\x43hat\x12\x19.myfirstgrpc.HelloRequest\x1a\x17.myfirstgrpc.HelloReply\"\x00(\x01\x30\x01\x12\x44\n\x0c\x44ownloadFile\x12\x18.myfirstgrpc.FileRequest\x1a\x16.myfirstgrpc.FileChunk\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myFirstGrpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=34
  _globals['_HELLOREQUEST']._serialized_end=62
  _globals['_HELLOREPLY']._serialized_start=64
  _globals['_HELLOREPLY']._serialized_end=93
  _globals['_FILEREQUEST']._serialized_start=95
  _globals['_FILEREQUEST']._serialized_end=126
  _globals['_FILECHUNK']._serialized_start=128
  _globals['_FILECHUNK']._serialized_end=156
  _globals['_GREETER']._serialized_start=159
  _globals['_GREETER']._serialized_end=518
# @@protoc_insertion_point(module_scope)
