# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import myFirstGrpc_pb2 as myFirstGrpc__pb2

GRPC_GENERATED_VERSION = '1.65.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in myFirstGrpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/myfirstgrpc.Greeter/SayHello',
                request_serializer=myFirstGrpc__pb2.HelloRequest.SerializeToString,
                response_deserializer=myFirstGrpc__pb2.HelloReply.FromString,
                _registered_method=True)
        self.StreamGreetings = channel.unary_stream(
                '/myfirstgrpc.Greeter/StreamGreetings',
                request_serializer=myFirstGrpc__pb2.HelloRequest.SerializeToString,
                response_deserializer=myFirstGrpc__pb2.HelloReply.FromString,
                _registered_method=True)
        self.SendGreetings = channel.stream_unary(
                '/myfirstgrpc.Greeter/SendGreetings',
                request_serializer=myFirstGrpc__pb2.HelloRequest.SerializeToString,
                response_deserializer=myFirstGrpc__pb2.HelloReply.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/myfirstgrpc.Greeter/Chat',
                request_serializer=myFirstGrpc__pb2.HelloRequest.SerializeToString,
                response_deserializer=myFirstGrpc__pb2.HelloReply.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/myfirstgrpc.Greeter/DownloadFile',
                request_serializer=myFirstGrpc__pb2.FileRequest.SerializeToString,
                response_deserializer=myFirstGrpc__pb2.FileChunk.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGreetings(self, request, context):
        """Server streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendGreetings(self, request_iterator, context):
        """Client streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """Bidirectional streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """File download
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=myFirstGrpc__pb2.HelloRequest.FromString,
                    response_serializer=myFirstGrpc__pb2.HelloReply.SerializeToString,
            ),
            'StreamGreetings': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGreetings,
                    request_deserializer=myFirstGrpc__pb2.HelloRequest.FromString,
                    response_serializer=myFirstGrpc__pb2.HelloReply.SerializeToString,
            ),
            'SendGreetings': grpc.stream_unary_rpc_method_handler(
                    servicer.SendGreetings,
                    request_deserializer=myFirstGrpc__pb2.HelloRequest.FromString,
                    response_serializer=myFirstGrpc__pb2.HelloReply.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=myFirstGrpc__pb2.HelloRequest.FromString,
                    response_serializer=myFirstGrpc__pb2.HelloReply.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=myFirstGrpc__pb2.FileRequest.FromString,
                    response_serializer=myFirstGrpc__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myfirstgrpc.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myfirstgrpc.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myfirstgrpc.Greeter/SayHello',
            myFirstGrpc__pb2.HelloRequest.SerializeToString,
            myFirstGrpc__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGreetings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/myfirstgrpc.Greeter/StreamGreetings',
            myFirstGrpc__pb2.HelloRequest.SerializeToString,
            myFirstGrpc__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendGreetings(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/myfirstgrpc.Greeter/SendGreetings',
            myFirstGrpc__pb2.HelloRequest.SerializeToString,
            myFirstGrpc__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/myfirstgrpc.Greeter/Chat',
            myFirstGrpc__pb2.HelloRequest.SerializeToString,
            myFirstGrpc__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/myfirstgrpc.Greeter/DownloadFile',
            myFirstGrpc__pb2.FileRequest.SerializeToString,
            myFirstGrpc__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
